### ISSUE TITLE
SyntaxError in JavaScript code for defaultSelectedColumns list

### ISSUE THREAD

**Issue by zagl** [engwerda/Django-Admin-Column-Toggle#2]
In Python the following definition of the list/tuple is valid code
```
default_selected_columns = ('status',)
```

But this translates to the following invalid JavaScript code which raises a SyntaxError
```
window.defaultSelectedColumns = ('status',);
```

The variable should be converted to a list before it is assigned as context variable

https://github.com/engwerda/Django-Admin-Column-Toggle/blob/310f4748d222e46be724d457b50f5ba5466fc11c/column_toggle/admin.py#L14-L17

This should be 

```
 context = { 
     "default_selected_columns": list(self.default_selected_columns), 
     "list_display": list(self.list_display), 
 } 
```

**Comment by engwerda** [comment]
This has been fixed in the latest version 0.4.0
